---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Get all users
      tags:
      - Users
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            email:
              type: string
          required:
          - id
          - name
          - email
      responses:
        '200':
          description: get users successfully
        '422':
          description: invalid request
  "/api/v1/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: body
        schema:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            email:
              type: string
          required:
          - id
          - name
          - email
      responses:
        '200':
          description: user found
        '404':
          description: user not found
        '406':
          description: unsupported accept header
